version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Identity.Stores
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: System.Private.ServiceModel
    versions:
    - 4.8.0
